language: objective-c
osx_image: xcode8
before_install: rvm use 2.0
install: gem install slather
script: xcodebuild test -project LeanCloud.xcodeproj -scheme LeanCloud -sdk iphonesimulator
after_success: slather
